[tool.poetry]
name = "clev2er"
version = "0.1.0"
description = "CLEV2ER LI+IW chain"
authors = ["Alan Muir <a.muir@ucl.ac.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11, <3.12"
numpy = "^1.24.3"
envyaml = "^1.10"
codetiming = "^1.4.0"
netcdf4 = "^1.6.3"
pyproj = "^3.5.0"
pygments = "^2.15.1"
scipy = "^1.10.1"
matplotlib = "^3.7.1"
tifffile = "^2023.4.12"
imagecodecs = "^2023.3.16"
rasterio = "^1.3.8"
xmltodict = "^0.13.0"
cartopy = "^0.22.0"
scikit-image = "^0.22.0"
zarr = "^2.18.2"


[tool.poetry.group.dev.dependencies]
black = "*"
pre-commit = "*"
pylint = "*"
isort = "*"
pytest = "^7.3.1"
sphinx = "^7.0.1"
sphinxcontrib-napoleon = "^0.7"
furo = "^2023.5.20"
pdoc = "^14.0.0"
mypy = "^1.3.0"
ruff = "^0.0.290"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
#use black profile so black and isort don't conflict
profile = "black"

[tool.pytest.ini_options]
markers = [
    "lrm",
    "sin",
]

[tool.mypy]
python_version="3.11"
ignore_missing_imports = true

[tool.ruff]
line-length = 100
select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  #"I",   # isort : could replace actual isort, but currently causes conflicts
 # "UP",  # pyupgrade
]
target-version = "py311"
#fixable = ["I"]
#fix = true

[tool.black]
line-length = 100
target-version = ['py311']

# Note pylint settings in .pylintrc

